---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: Schedule
- type: directory
  path: content/Programs
  label: Programs
  create: all
  match: "**/*"
  templates:
  - program
- type: directory
  path: content/Sessions
  label: Sessions
  create: all
  match: "**/*"
  templates:
  - session
- type: directory
  path: content/Meetings
  label: Meetings
  create: all
  match: "**/*"
  templates:
  - meeting
- type: heading
  label: People
- type: directory
  path: content/Mentors
  label: Mentors
  create: all
  match: "**/*"
  templates:
  - people
- type: directory
  path: content/Fellows
  label: Fellows
  create: all
  match: "**/*"
  templates:
  - people
- type: directory
  path: content/Steering_Committee
  label: Steering Committee
  create: all
  match: "**/*"
  templates:
  - people
- type: directory
  path: content/Chairs
  label: Chairs
  create: all
  match: "**/*"
  templates:
  - people
- type: heading
  label: Other
- type: directory
  path: content/Blog
  label: Blog
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: directory
  path: content/Pages_content
  label: Pages
  create: all
  match: "**/*"
- type: directory
  path: content/Institutions
  label: Institutions
  create: all
  match: "**/*"
  templates:
  - institution
- type: directory
  path: content/testimonials
  label: Testimonials
  create: all
  match: "**/*"
- type: directory
  path: content/Partners_and_Sponsors
  label: Partners and Sponsors
  create: all
  match: "**/*"
  templates:
  - institution
- type: directory
  path: content/Carousel
  label: Carousel
  create: all
  match: "**/*"
  templates:
  - carousel-item
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
